#!/bin/sh
xrandr --dpi 136 --output VIRTUAL1 --off --output eDP-1 --primary --mode 2560x1440 --pos 0x720 --rotate normal --output DP-1 --off --output DP-2-1 --mode 3840x2160 --pos 2560x0 --rotate normal --output DP-2-2 --off --output DP-2-3 --off --output HDMI-2 --off --output HDMI-1 --off --output DP2 --off
