#!/bin/sh
xrandr --dpi 136 --output VIRTUAL1 --off --output eDP1 --primary --mode 2560x1440 --pos 0x720 --rotate normal --output DP1 --off --output DP2-1 --mode 3840x2160 --pos 2560x0 --rotate normal --output DP2-2 --off --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
i3-msg restart
