#!/bin/sh
xrandr --output HDMI-1-2 --off --output HDMI-1-1 --off --output DP-1-2-1 --off --output eDP-1-1 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1-2-2 --off --output DP-1-2-3 --off --output DP-1-2 --off --output DP-1-1 --off
