#!/bin/sh
xrandr --output VIRTUAL-1 --off --output eDP-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --off --output HDMI-2 --mode 1920x1080 --pos 2560x0 --rotate normal --output HDMI-1 --off --output DP-2 --off
i3-msg restart
