dialect = "us"
search_mode = "fuzzy"
style = "compact"
ctrl_n_shortcuts = true
enter_accept = true
inline_height = 15
filter_mode = "global"
filter_mode_shell_up_key_binding = "session"
show_preview = true
