theme: gruvbox-dark
ui:
  pane_frames:
    rounded_corners: true
scroll-buffer-size: 100000
layout: compact

keybinds:
  normal:
    - unbind: [Ctrl: 't',]
    - action: [SwitchToMode: Tab,]
      key: [Ctrl: 'y']
    - unbind: [Ctrl: 'h',]
    - action: [SwitchToMode: Move,]
      key: [Ctrl: 'm']
  resize:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  pane:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  move:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  tab:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  scroll:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  session:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  search:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
  tmux:
    - action: [SwitchToMode: Normal,]
      key: [Char: 'q']
    - action: [NewPane: Down, SwitchToMode: Normal,]
      key: [Char: '-',]
    - action: [NewPane: Right, SwitchToMode: Normal,]
      key: [Char: '|',]
    - unbind: [Char: "\"",]
    - unbind: [Char: '%',]
